language: go

go:
  - 1.14.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)